# https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup
dbt_demo: # dbt_demo name. This is where dbt looks for from dbt_project.yml -> find the named profile here. Can also be overwritten by dbt run --profiles. See dbt run --help for more info
  target: jaffle_sql # default target for profile, points to 1 of the output below # define target in dbt CLI via --target
  outputs:
    threads: 1 # Must be a value of 1 or greater 
    location: US
    priority: interactive
    jaffle_sql: # target 2
      type: bigquery
      method: oauth 
      project: "sctp-dsai-ds3"
      dataset: "jaffle_demo"
      retries: 1